---
# tasks file for template
- name: Ensure ansible_facts used by role
  when: not ansible_facts.keys() | list |
    intersect(template_required_facts) == template_required_facts
  ansible.builtin.setup:
    gather_subset: min

- name: Include distribution/version specific variables
  when: template_vars_file is file
  ansible.builtin.include_vars: "{{ template_vars_file }}"
  loop:
#    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    template_vars_file: "{{ role_path }}/vars/distributions/{{ item }}"
