---
# tasks file for template

- name: Install packages
  when: template_packages is defined
  ansible.builtin.package:
    name: "{{ template_packages }}"
    state: present

- name: Remove packages
  when: template_packages_to_remove is defined
  ansible.builtin.package:
    name: "{{ template_packages_to_remove }}"
    state: present
